"""add player role field

Revision ID: d880adf9d051
Revises: c5d9e2f6a3b7
Create Date: 2026-06-13 17:15:58.326899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd880adf9d051'
down_revision = 'c5d9e2f6a3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False, server_default='member'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
